#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FlatUI.Resource", IsApplication=false)]

namespace FlatUI
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000a
			public static int backgroundColor = 2130771978;
			
			// aapt resource value: 0x7f010004
			public static int cornerRadius = 2130771972;
			
			// aapt resource value: 0x7f01000b
			public static int customBackgroundColor = 2130771979;
			
			// aapt resource value: 0x7f010008
			public static int fieldStyle = 2130771976;
			
			// aapt resource value: 0x7f010002
			public static int fontFamily = 2130771970;
			
			// aapt resource value: 0x7f010003
			public static int fontWeight = 2130771971;
			
			// aapt resource value: 0x7f010007
			public static int isFullFlat = 2130771975;
			
			// aapt resource value: 0x7f010006
			public static int size = 2130771974;
			
			// aapt resource value: 0x7f010001
			public static int textAppearance = 2130771969;
			
			// aapt resource value: 0x7f010009
			public static int textColor = 2130771977;
			
			// aapt resource value: 0x7f010005
			public static int textPadding = 2130771973;
			
			// aapt resource value: 0x7f010000
			public static int theme = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f030003
			public static int Comfortaa = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int DroidSans = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int OpenSans = 2130903045;
			
			// aapt resource value: 0x7f030006
			public static int Roboto = 2130903046;
			
			// aapt resource value: 0x7f030007
			public static int bold = 2130903047;
			
			// aapt resource value: 0x7f03000b
			public static int box = 2130903051;
			
			// aapt resource value: 0x7f030000
			public static int dark = 2130903040;
			
			// aapt resource value: 0x7f03000e
			public static int darker = 2130903054;
			
			// aapt resource value: 0x7f030008
			public static int extrabold = 2130903048;
			
			// aapt resource value: 0x7f030009
			public static int extralight = 2130903049;
			
			// aapt resource value: 0x7f03000c
			public static int flat = 2130903052;
			
			// aapt resource value: 0x7f030001
			public static int light = 2130903041;
			
			// aapt resource value: 0x7f03000f
			public static int main = 2130903055;
			
			// aapt resource value: 0x7f030002
			public static int none = 2130903042;
			
			// aapt resource value: 0x7f03000a
			public static int regular = 2130903050;
			
			// aapt resource value: 0x7f03000d
			public static int transparent = 2130903053;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f020000
			public static int library_name = 2130837504;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FlatUI = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 10
			public static int FlatUI_backgroundColor = 10;
			
			// aapt resource value: 4
			public static int FlatUI_cornerRadius = 4;
			
			// aapt resource value: 11
			public static int FlatUI_customBackgroundColor = 11;
			
			// aapt resource value: 8
			public static int FlatUI_fieldStyle = 8;
			
			// aapt resource value: 2
			public static int FlatUI_fontFamily = 2;
			
			// aapt resource value: 3
			public static int FlatUI_fontWeight = 3;
			
			// aapt resource value: 7
			public static int FlatUI_isFullFlat = 7;
			
			// aapt resource value: 6
			public static int FlatUI_size = 6;
			
			// aapt resource value: 1
			public static int FlatUI_textAppearance = 1;
			
			// aapt resource value: 9
			public static int FlatUI_textColor = 9;
			
			// aapt resource value: 5
			public static int FlatUI_textPadding = 5;
			
			// aapt resource value: 0
			public static int FlatUI_theme = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
